### ISSUE TITLE
Call to undefined function Swagger\scan()

### ISSUE THREAD

**Issue by zasyadev** [DarkaOnLine/L5-Swagger#161]
- L5-Swagger Version: 5.6.*
- PHP Version 7.1
- OS: ubuntu16.04

Description:  facing this issue after composer update

**Comment by DarkaOnLine** [comment]
You need to require swager-php 2.*: `composer require zircote/swagger-php:2.*`

**Comment by DarkaOnLine** [comment]
Please follow #159 for further updates.

**Comment by flik** [comment]
I had the same issue and then fixed with this:

`./vendor/bin/swagger app/Http --output storage/api-docs`

It will generate the json file with the name swagger.json.
You need to rename it with the name api-docs.json and then access the url:
http://localhost/angular-laravel/public/api/documentation

I have installed in composer json:

```
 "require": {
        "php": "^7.1.3",
        "barryvdh/laravel-cors": "^0.11.0",
        "darkaonline/l5-swagger": "5.7.*",
        "fideloper/proxy": "^4.0",
        "folklore/graphql": "^1.1",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "zircote/swagger-php": "2.*"
    },
```
