### ISSUE TITLE
Cant send multiple files

### ISSUE THREAD

**Issue by YaakovDantas** [DarkaOnLine/L5-Swagger#255]
- L5-Swagger Version: 5.5.8.3 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.0.33
- OS: Ubuntu 19

### Description:
Cant send multiple files array, it's going like string "[object File],[object File]"

### Steps To Reproduce:

    *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="multipart/form-data",
     *             @OA\Schema(
     *                @OA\Property(
     *                    property="arquivos",
     *                    type="array",
     *                    description="Documento para enviar, menor igual que 5MB, formatos (.doc, .docx, .pdf)",
     *                    @OA\Items(type="string", format="binary"),
     *                 ),

**Comment by DarkaOnLine** [comment]
This looks like swagger-ui limitation: https://github.com/swagger-api/swagger-ui/issues/4600 not this package issue :(

**Comment by kkls-mike** [comment]
If anyone still faces that issue, with 3.26.0 release (https://github.com/swagger-api/swagger-ui/releases/tag/v3.26.0) of swagger-api/swagger-ui package uploading multiple files became possible, so doing 

`composer update swagger-api/swagger-ui`

worked for me. This one 

> @OA\Property(
     *     property="files[]",
     *     description="Files to upload",
     *     type="array",
     *     @OA\Items(type="string", format="binary")
     * ),

in my multipart/form-data schema now sends an array of files instead of "[object File],[object File]" string. Please note that property field should include box brackets.
