### ISSUE TITLE
Put server host from config or change on run time.

### ISSUE THREAD

**Issue by bliveinhack** [DarkaOnLine/L5-Swagger#313]
- L5-Swagger Version: 6.* (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):  7.4.2
- OS: Windows

### Description:
Hi, Thanks for the great pkg.

I am using app that is multi tenant. so basically i want server URL to be domain i have specified in tenant.
I have tried tacking app url from config but it doesn't work.

### Steps To Reproduce:
- Just try change L5_SWAGGER_CONST_HOST to be set from database or problematically and see if it works.

**Comment by DarkaOnLine** [comment]
Defined constants are replaced during docs generation and constant should be in annotation like this
```
/**
 *  @OA\Server(
 *      url=YOUR_DYNAMIC_URL_CONSTANT,
 *      description="L5 Swagger OpenApi dynamic host server"
 *  )
*/
```

And you have to define it in config or by your self before generation process kicks in like this:
```php
defined('YOUR_DYNAMIC_URL_CONSTANT') || define('YOUR_DYNAMIC_URL_CONSTANT', 'https://your-dynamic-url.com');
```

Or instead of `'https://your-dynamic-url.com'` you can call your function which will get URL from DB

**Comment by ThallesBogarPortilho** [comment]
I'm not sure where to put this:

`defined('YOUR_DYNAMIC_URL_CONSTANT') || define('YOUR_DYNAMIC_URL_CONSTANT', 'https://your-dynamic-url.com');`

Would it be inside l5-swagger.php file?
