### ISSUE TITLE
Possible to use oauth2 password flow for Try button?

### ISSUE THREAD

**Issue by bandtank** [DarkaOnLine/L5-Swagger#32]
I'm confused about how to implement the Try button with the Oauth2 password flow. Actually, I can't get the button to work with any Oauth2 flow, but password is the one I'd like to use. I've been searching online for a while and I found a [link](https://github.com/noirbizarre/flask-restplus/issues/138) that kinda says how to do it, but it lacks most of the relevant information to actually tell someone how to make it work (like usual... people always post the minimal amount of info and expect everyone to already understand... /sigh).

I've looked in config/l5-swagger.php and I can't find any settings in there related to Oauth2. I see the api_key field, but I don't really know what to do with that either or if there's a way to use that. The Try button works with endpoints that don't need a token, so I know my documentation and API are functioning correctly up to that point.

Any tips would be greatly appreciated.

**Comment by DarkaOnLine** [comment]
Sorry but I personally didn't try to implement Oauth2,  so I can't help you with this issue :(

**Comment by frol** [comment]
@bandtank I am really a stranger here as I am on the Python side of things, but since you have referenced the issue I was taking care of, and I accidentally read this issue, I spent a couple of moments to investigate the code of the current project to find that you needed to trigger this code: https://github.com/DarkaOnLine/L5-Swagger/blob/ba92fedf85556db7de354f2a7b5a959a690e65a0/resources/views/index.blade.php#L75-L83 and modify the values there somehow. HOWEVER, the refactored OAuth2 code in Swagger UI seems to ignore this `initOAuth` way of setting OAuth configs and I am not sure what the new way is... Good luck.
