### ISSUE TITLE
CORS issue on live site

### ISSUE THREAD

**Issue by bandtank** [DarkaOnLine/L5-Swagger#38]
I'm able to load the documentation for my API with no issues locally using http, but it doesn't work on heroku using https. I've struggled with CORS for quite some time, so I'm not surprised at this and I'm also not even sure it's l5-swagger causing the problem, but I figured I'd start here given what I'm seeing.

I have the routes setup as `/documentation` and `/docs` in `config/l5-swagger.php`. Going to `/documentation` loads the page and all documentation as expected locally. This is what happens when I navigate to my documentation page on Heroku over https:

![image](https://cloud.githubusercontent.com/assets/1170415/19714451/74e03dde-9b0b-11e6-9065-45f0af7d4850.png)

I don't understand why the link is set to http. I've looked through my code for a long time and I can't figure out where that url is generated. I see a PHP variable called `$urlToDocs`. The page loads just fine if I use the CORS chrome plugin:

![2016-10-25_23-34-07](https://cloud.githubusercontent.com/assets/1170415/19714511/2749d5c0-9b0c-11e6-8e3b-5ea440d86e84.png)

**Comment by DarkaOnLine** [comment]
Please check your `config/app.php` -> https://github.com/laravel/laravel/blob/master/config/app.php#L54

**Comment by DarkaOnLine** [comment]
And also `.env` file for: `APP_URL`.

**Comment by bandtank** [comment]
![image](https://cloud.githubusercontent.com/assets/1170415/19715184/b4472e24-9b10-11e6-99b2-5303de8e5be8.png)

It still shows as http in the debug window even after making the changes shown above.

**Comment by DarkaOnLine** [comment]
can you lounch `php artisan tinker` and when execute command:

`route('l5-swagger.docs', config('l5-swagger.paths.docs_json', 'api-docs.json'))`

which URL does it return ?

**Comment by bandtank** [comment]
Heroku and localhost shown for completeness:

![image](https://cloud.githubusercontent.com/assets/1170415/19715504/dce5424c-9b12-11e6-931e-7f39c7be2221.png)

**Comment by DarkaOnLine** [comment]
it looks like the issue is related with Heroku. Quick googling https://devcenter.heroku.com/articles/getting-started-with-laravel

`
Heroku’s HTTP Routing routes each request through a layer of reverse proxies which are, among other things, responsible for load balancing and terminating SSL connections. This means that requests received by a dyno will have the last router’s IP address in the REMOTE_ADDR environment variable, and the internal request will always be made using the HTTP protocol, even if the original request was made over HTTPS.
`

I think you should read more about this, because this is not a package problem.

**Comment by DarkaOnLine** [comment]
You can try adding this into the `AppServiceProvider.php`

```php
public function boot()
{
     if (!\App::environment('local')) {
          \URL::forceSchema('https');
     }
}
```

**Comment by bandtank** [comment]
Thanks for taking the time to find that link about the Heroku routing issue. That has to be the problem.
