### ISSUE TITLE
Error while updating L5-Swagger v. 8.2.0

### ISSUE THREAD

**Issue by stavtsob** [DarkaOnLine/L5-Swagger#444]
- L5-Swagger Version: 8.2.0 (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): PHP 7.4.3 
- OS: Ubuntu 20.04 lts

### Description:

After a composer update, I got the new version of l5-swagger, but a strange error appeared.
I have a custom package that uses swagger comment annotations, but while doing the 'composer update' all the content of the blade files, where echoed to the console.
After that, an error appeared:

   Symfony\Component\ErrorHandler\Error\FatalError

  Cannot redeclare Composer\Autoload\includeFile() (previously declared in /.............../vendor/composer/ClassLoader.php:478)

**Comment by DerManoMann** [comment]
Updating your dependencies should help. This is caused by a version of swagger-php that actively loads files to ensure the contained classes are available for reflection.

However, if your files are blade template files this might still not work as expected, as swagger-php v4 requires annotations to be associated with a class/interface/etc. in order to have a 'hook' for reflection.

Annotations that do not 'annotate' something will no longer work.

More details can be found here: https://zircote.github.io/swagger-php/guide/faq and here: https://zircote.github.io/swagger-php/guide/migrating-to-v4
